### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/vue-sfc-rollup/templates/library/.gitignore

### ISSUE THREAD

**Issue by jasonbosco** [team-innovation/vue-sfc-rollup#104]
I just ran into this error when running `sfc-init`:

```shellsession
$ sfc-init
✔ Which version of Vue are you writing for? › Vue 2
✔ Is this a single component or a library? › Library
✔ What is the npm name of your library? … vuepress-plugin-typesense-search
✔ Will this library be written in JavaScript or TypeScript? › JavaScript
✔ Enter a location to save the library files: … ./vuepress-plugin-typesense-search
(node:86758) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/vue-sfc-rollup/templates/library/.gitignore'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at /usr/local/lib/node_modules/vue-sfc-rollup/sfc-init.js:284:21
    at Array.forEach (<anonymous>)
    at scaffold (/usr/local/lib/node_modules/vue-sfc-rollup/sfc-init.js:260:15)
    at /usr/local/lib/node_modules/vue-sfc-rollup/sfc-init.js:324:5
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:86758) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:86758) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

$ cat /usr/local/lib/node_modules/vue-sfc-rollup/templates/library/.gitignore
cat: /usr/local/lib/node_modules/vue-sfc-rollup/templates/library/.gitignore: No such file or directory

$ $ ls -al /usr/local/lib/node_modules/vue-sfc-rollup/templates/library/
total 28
drwxr-xr-x 12 jason  384 Jul 23 12:11 .
drwxr-xr-x  4 jason  128 Jul 23 12:11 ..
-rw-r--r--  1 jason   46 Oct 26  1985 .browserslistrc
-rw-r--r--  1 jason  216 Oct 26  1985 .npmignore
-rw-r--r--  1 jason  470 Oct 26  1985 babel.config.js
drwxr-xr-x  3 jason   96 Jul 23 12:11 build
drwxr-xr-x  4 jason  128 Jul 23 12:11 dev
-rw-r--r--  1 jason 2540 Oct 26  1985 library-package.json
-rw-r--r--  1 jason  305 Oct 26  1985 shims-tsx.d.ts
-rw-r--r--  1 jason  246 Oct 26  1985 shims-vue.d.ts
drwxr-xr-x  5 jason  160 Jul 23 12:11 src
-rw-r--r--  1 jason 1008 Oct 26  1985 tsconfig.json
```

I'm using the latest published version `v4.1.0`. It looks like the `.gitignore` template file didn't make it into the published npm package?

**Comment by mgdodge** [comment]
Thanks for reporting this! I've seen this happen before, where npm won't publish certain files, even in subdirectories. Will get a fix out ASAP.

**Comment by mgdodge** [comment]
Fix is out on npm.

**Comment by mgdodge** [comment]
Closing, updated repo with 4.1.1 code
