### ISSUE TITLE
Trouble during sfc-rollup-init

### ISSUE THREAD

**Issue by markrmessmore** [team-innovation/vue-sfc-rollup#8]
To verify I have done the following steps:
```
npm install -g vue-sfc-rollup
sfc-rollup-init
What is the npm name of your component? v-tourney
What is the kebab-case tag name for your component? (v-tourney) vTourney
Enter a location to save the component files: (./vTourney)
```

Upon hitting ***enter*** I receive the following error:

```
fs.js:126
    throw err;

Error: ENOENT: no such file or directory, open 'C:\Users\markr\AppData\Roaming\npm\node_modules\vue-sfc-rollup\templates\single\package.json'
    at Object.fs.openSync (fs.js:559:3)
    at Object.fs.readFileSync (fs.js:465:33)
    at Object.<anonymous> (C:\Users\markr\AppData\Roaming\npm\node_modules\vue-sfc-rollup\sfc-init.js:85:8)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
```

**Comment by mgdodge** [comment]
Oops! Looks like the alpha was published globally, and it is not uploading some of the required files! Thanks for catching this! The alpha is pretty much done, republishing shortly.
